# Generated by Django 5.0.6 on 2026-09-23 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('property_type', models.CharField(choices=[('PG', 'PG'), ('Hostel', 'Hostel'), ('Room', 'Room'), ('Apartment', 'Apartment')], default='PG', max_length=20)),
                ('location', models.CharField(db_index=True, max_length=120)),
                ('address', models.TextField()),
                ('monthly_rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('gender_preference', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=10)),
                ('food_available', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('laundry_available', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
